### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by antonkluev** [MethodGrab/atom-set-indent#1]
i have Atom 1.16.0 x64 on Mac, if i try to run the conversion, it doesn't work

**Comment by MethodGrab** [comment]
> ...it doesn't work

Please could you clarify what you mean by this.

The purpose of the package is to quickly change the editor settings to a new indent style & size (the same as going to `File -> Settings -> Editor` and changing the `Soft Tabs` & `Tab Length` options) _only for the file that is active/focused when you run the command_.

It is **not** intended to convert documents from one indentation style/size to another, it will **not** reformat any code.

I apologise if the description was unclear or misleading, if this is the case I'm happy to amend it?

I've just re-run the CI tests against Atom 1.16 stable on Mac & Linux and tested it manually on Windows and for me it appears to be working as expected.

If you are still having an issue with the way the package is intended to function please provide some more details (such as steps to reproduce) so I can investigate further.

**Comment by antonkluev** [comment]
sooo... my file has mixed (soft and hard) indents. As i try to run the conversion from a command palette, it does nothing in any direction (doesn't convert all to soft or hard tabs).

**Comment by MethodGrab** [comment]
As I said, converting documents from one indent style/size to another is **not** what this package does.
All this package does is temporarily change what happens (tabs / spaces & the length) when you press the <kbd>Tab</kbd> key.

There are **other** packages that handle converting from one style to another.

**Comment by antonkluev** [comment]
ah... okay :P thank you!
