### ISSUE TITLE
Add Sublime-like indent menu in footer

### ISSUE THREAD

**Issue by filipre** [MethodGrab/atom-set-indent#2]
Hi,
package works fine for me, thanks! Just a small proposal: It would be nice to show and change the current indent in the footer of Atom like Sublime does it:

![sublime](https://i.imgur.com/vIUHhjI.png)

Maybe it even makes sense to apply the change to the current document. Would make the plugin much more valuable.

Cheers
René

**Comment by MethodGrab** [comment]
Good idea!

**Comment by MethodGrab** [comment]
Published as v1.0.0.
